import './globals.css'
import { Inter } from 'next/font/google'
import Provider from './Provider'
import { Header } from './common/components'
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Header height={60} p="xs" className='items-center flex gap-5'>
            <Link href="/">Home</Link>
            <Link href="/about">About</Link>
            <Link href="/about/detail">Detail</Link>
          </Header>
          {children}
        </Provider>
      </body>
    </html>
  )
}
